import type { DBStudent, DBClassroom, DBSubject, AttendanceYearlyRow } from "../types";

interface AttendanceTabProps {
  mySubjects: DBSubject[]; attendanceSubjectId: string; onSelectSubject: (id: string) => void;
  attendanceClassroomId: string; setAttendanceClassroomId: (id: string) => void;
  attendanceClassroomOptions: DBClassroom[]; attendanceClassroomStudents: DBStudent[];
  attendanceRows: Record<string, AttendanceYearlyRow>; totalWeeks: number;
  attendanceLoading: boolean; attendanceSaving: boolean;
  onSetDays: (studentId: string, field: keyof Omit<AttendanceYearlyRow, "student_id">, value: string) => void;
  onSaveRow: (student: DBStudent) => void; onSaveAll: () => void;
}

export default function AttendanceTab(props: AttendanceTabProps) {
  const { mySubjects, attendanceSubjectId, onSelectSubject, attendanceClassroomId, setAttendanceClassroomId, attendanceClassroomOptions, attendanceClassroomStudents, attendanceRows, totalWeeks, attendanceLoading, attendanceSaving, onSetDays, onSaveRow, onSaveAll } = props;
  const selectedSubject = mySubjects.find(s => s.id === attendanceSubjectId);
  const selectedClassroom = attendanceClassroomOptions.find(c => c.id === attendanceClassroomId);
  const inputClass = "w-16 sm:w-20 rounded-lg border border-border bg-card px-1.5 py-1.5 text-center text-xs sm:text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-400";
  const renderStudent = (student: DBStudent, index: number, mobile = false) => {
    const row = attendanceRows[student.student_id] ?? { student_id: student.student_id, present_days: 0, sick_leave_days: 0, personal_leave_days: 0 };
    const used = row.present_days + row.sick_leave_days + row.personal_leave_days;
    const fields = [{ key: "present_days" as const, label: "มาเรียน" }, { key: "sick_leave_days" as const, label: "ลาป่วย" }, { key: "personal_leave_days" as const, label: "ลากิจ" }];
    if (mobile) return <div key={student.id} className="rounded-2xl border border-border bg-card p-4 space-y-3"><div className="flex items-start justify-between gap-3"><div><div className="font-bold text-sm">{index + 1}. {student.name}</div><div className="text-xs text-indigo-600 font-semibold">{student.student_id}</div></div><button type="button" onClick={() => onSaveRow(student)} disabled={attendanceSaving} className="px-3 py-2 rounded-lg bg-indigo-600 text-white text-xs font-bold disabled:opacity-50">บันทึก</button></div><div className="grid grid-cols-3 gap-2">{fields.map(field => <label key={field.key} className="text-center"><span className="block text-[11px] text-muted-foreground mb-1">{field.label}</span><input type="number" min="0" max={Math.max(0, totalWeeks - (used - row[field.key]))} value={row[field.key]} onChange={e => onSetDays(student.student_id, field.key, e.target.value)} className={`${inputClass} w-full`} /></label>)}</div><div className="flex justify-between text-xs font-bold border-t border-border pt-2"><span>รวม {used} / {totalWeeks}</span><span className="text-rose-600">ขาดเรียน {Math.max(0, totalWeeks - used)} วัน</span><span className="text-indigo-600">{((row.present_days / totalWeeks) * 100).toFixed(1)}%</span></div></div>;
    return <tr key={student.id}><td className="px-4 py-3 text-muted-foreground">{index + 1}</td><td className="px-4 py-3 font-semibold">{student.name}<div className="text-xs text-indigo-600">{student.student_id}</div></td>{fields.map(field => <td key={field.key} className="px-4 py-3 text-center"><input type="number" min="0" max={Math.max(0, totalWeeks - (used - row[field.key]))} value={row[field.key]} onChange={e => onSetDays(student.student_id, field.key, e.target.value)} className={inputClass} /></td>)}<td className="px-4 py-3 text-center font-bold">{used} / {totalWeeks}</td><td className="px-4 py-3 text-center font-bold text-rose-600">{Math.max(0, totalWeeks - used)}</td><td className="px-4 py-3 text-center font-bold text-indigo-600">{((row.present_days / totalWeeks) * 100).toFixed(1)}%</td><td className="px-4 py-3 text-center"><button type="button" onClick={() => onSaveRow(student)} disabled={attendanceSaving} className="px-3 py-1.5 rounded-lg bg-indigo-600 text-white text-xs font-bold disabled:opacity-50">บันทึก</button></td></tr>;
  };
  return <div className="space-y-5">
    {!attendanceSubjectId && <div className="card-modern p-5"><div className="font-bold text-sm mb-4">เลือกวิชา</div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{mySubjects.map(s => <button key={s.id} onClick={() => onSelectSubject(s.id)} className="p-4 rounded-xl border border-border bg-card text-left font-bold hover:border-indigo-400">{s.name}</button>)}</div></div>}
    {attendanceSubjectId && !attendanceClassroomId && <div className="card-modern p-5"><div className="flex items-center gap-3 mb-4"><button onClick={() => onSelectSubject("")} className="px-3 py-2 rounded-lg border border-border text-sm font-bold">ย้อนกลับ</button><div className="font-bold text-sm">เลือกชั้นเรียน: {selectedSubject?.name}</div></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">{attendanceClassroomOptions.map(c => <button key={c.id} onClick={() => setAttendanceClassroomId(c.id)} className="rounded-xl border border-border bg-card py-4 font-bold hover:border-indigo-400">{c.name}</button>)}</div></div>}
    {attendanceSubjectId && attendanceClassroomId && <div className="card-modern overflow-hidden"><div className="p-4 sm:p-5 border-b border-border flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><button onClick={() => setAttendanceClassroomId("")} className="px-3 py-2 rounded-lg border border-border text-sm font-bold">ย้อนกลับ</button><div><div className="font-bold text-sm">เช็คชื่อ: {selectedSubject?.name} / {selectedClassroom?.name}</div><p className="text-xs text-muted-foreground mt-1">ลาป่วยและลากิจไม่นับเป็นวันมาเรียน</p></div></div><span className="rounded-xl px-3 py-2 text-xs font-bold bg-indigo-50 text-indigo-700">จำนวนสัปดาห์: {totalWeeks || "ยังไม่ได้กำหนด"}</span></div>{totalWeeks === 0 ? <div className="p-7 text-center text-amber-700 text-sm font-semibold">แอดมินต้องกำหนดจำนวนสัปดาห์ก่อนบันทึก</div> : attendanceLoading ? <div className="p-8 text-center text-muted-foreground">กำลังโหลดข้อมูล...</div> : <><div className="md:hidden p-3 space-y-3">{attendanceClassroomStudents.map((s, i) => renderStudent(s, i, true))}</div><div className="hidden md:block overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground"><th className="px-4 py-3 text-left">#</th><th className="px-4 py-3 text-left">ชื่อ-สกุล</th><th className="px-4 py-3 text-center">มาเรียน</th><th className="px-4 py-3 text-center">ลาป่วย</th><th className="px-4 py-3 text-center">ลากิจ</th><th className="px-4 py-3 text-center">รวม</th><th className="px-4 py-3 text-center">ขาดเรียน</th><th className="px-4 py-3 text-center">% มาเรียน</th><th className="px-4 py-3 text-center">บันทึก</th></tr></thead><tbody className="divide-y divide-border">{attendanceClassroomStudents.map((s, i) => renderStudent(s, i))}</tbody></table></div><div className="p-4 border-t border-border flex justify-end"><button onClick={onSaveAll} disabled={attendanceSaving} className="px-5 py-2.5 rounded-xl bg-indigo-600 text-white font-bold text-sm disabled:opacity-50">{attendanceSaving ? "กำลังบันทึก..." : "บันทึกทั้งหมด"}</button></div></>}</div>}
  </div>;
}
